import { mkdtempSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import ts from "typescript";
import { afterAll, describe, expect, it } from "vitest";
import { generateSequenceTypes, collectSteps } from "../typegen/index.js";
import { runCli } from "../typegen/cli.js";

const fixturePath = resolve(process.cwd(), "testdata/typegen/checkout.json");
const fixture = JSON.parse(readFileSync(fixturePath, "utf8"));
const tmp = mkdtempSync(join(tmpdir(), "orch8-typegen-"));
afterAll(() => rmSync(tmp, { recursive: true, force: true }));

const EXPECTED = `// Generated by orch8-typegen-v1 from sequence "checkout-flow". Do not edit.
/* eslint-disable */

/** Instance input (\`context.data\`), from \`input_schema\`. */
export type CheckoutFlowInput = {
  channel?: "web" | "mobile";
  coupon?: string | null;
  items: CheckoutFlowInputLineItem[];
  order_id: string;
};

export type CheckoutFlowInputLineItem = {
  qty: number;
  sku: string;
};

/** Output of step \`charge\` (handler \`payments.charge\`). */
export type CheckoutFlowChargeOutput = {
  "amount-cents"?: number;
  /** Provider charge id */
  charge_id: string;
  status: "succeeded";
  [key: string]: unknown;
};

/** Output of step \`sms\` (handler \`send-sms\`). */
export type CheckoutFlowSmsOutput = {
  sid: string;
} | null;

/** Output of step \`receipt\` (handler \`send-email\`). */
export type CheckoutFlowReceiptOutput = [string, number];

/** Step id → output type. Steps without \`output_schema\` are \`unknown\`. */
export interface CheckoutFlowStepOutputs {
  charge: CheckoutFlowChargeOutput;
  email: unknown;
  sms: CheckoutFlowSmsOutput;
  receipt: CheckoutFlowReceiptOutput;
}

export type CheckoutFlowStepId = keyof CheckoutFlowStepOutputs;

/** Worker handler name → step ids it serves. */
export interface CheckoutFlowHandlers {
  "payments.charge": "charge";
  "send-email": "email" | "receipt";
  "send-sms": "sms";
}
`;

function typecheck(source: string): string[] {
  const file = join(tmp, `check-${Math.random().toString(16).slice(2)}.ts`);
  writeFileSync(file, `${source}\nconst _probe: CheckoutFlowInput = { order_id: "o", items: [{ sku: "a", qty: 1 }] };\nexport { _probe };\n`);
  const program = ts.createProgram([file], { strict: true, noEmit: true, target: ts.ScriptTarget.ES2022, skipLibCheck: true });
  return ts.getPreEmitDiagnostics(program).map((d) => ts.flattenDiagnosticMessageText(d.messageText, "\n"));
}

function shuffleKeys(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(shuffleKeys);
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.entries(value).reverse().map(([k, v]) => [k, shuffleKeys(v)]));
  }
  return value;
}

describe("orch8-typegen", () => {
  it("collects nested steps and ignores params payloads", () => {
    expect(collectSteps(fixture).map((s) => s.id)).toEqual(["charge", "email", "sms", "receipt"]);
  });

  it("generates the expected declarations", () => {
    expect(generateSequenceTypes(fixture)).toBe(EXPECTED);
  });

  it("is deterministic across runs and object key order", () => {
    expect(generateSequenceTypes(shuffleKeys(fixture) as Record<string, unknown>)).toBe(EXPECTED);
    expect(generateSequenceTypes(fixture)).toBe(generateSequenceTypes(JSON.parse(JSON.stringify(fixture))));
  });

  it("emits TypeScript that compiles under strict mode", () => {
    expect(typecheck(EXPECTED)).toEqual([]);
  });

  it("handles recursive refs, allOf, nullable and open maps", () => {
    const out = generateSequenceTypes({
      name: "tree",
      input_schema: {
        $ref: "#/definitions/node",
        definitions: {
          node: {
            type: "object",
            required: ["children"],
            additionalProperties: false,
            properties: { children: { type: "array", items: { $ref: "#/definitions/node" } } },
          },
        },
      },
      blocks: [
        { type: "step", id: "a", handler: "h", output_schema: { allOf: [{ type: "object", properties: { x: { type: "string" } }, additionalProperties: false }, { type: "object", properties: { y: { type: "number", nullable: true } }, additionalProperties: false }] } },
        { type: "step", id: "b", handler: "h", output_schema: { type: "object", additionalProperties: { type: "integer" } } },
      ],
    });
    expect(out).toContain("export type TreeInput = TreeInputNode;");
    expect(out).toContain("children: TreeInputNode[];");
    expect(out).toContain("export type TreeBOutput = Record<string, number>;");
    expect(out).toMatch(/export type TreeAOutput = \{\n  x\?: string;\n\} & \{\n  y\?: number \| null;\n\};/);
  });

  it("CLI writes files and --check detects drift", async () => {
    const io = { stdout: () => {}, stderr: () => {}, env: {}, cwd: tmp };
    const out = join(tmp, "gen", "checkout.ts");
    expect(await runCli([fixturePath, "--out", out], io)).toBe(0);
    expect(readFileSync(out, "utf8")).toBe(EXPECTED);
    expect(await runCli([fixturePath, "--out", out, "--check"], io)).toBe(0);
    writeFileSync(out, "stale");
    expect(await runCli([fixturePath, "--out", out, "--check"], io)).toBe(1);
    expect(await runCli(["--bogus"], io)).toBe(2);
  });

  it("CLI --remote uses the engine dataflow endpoint and fails on error findings", async () => {
    const requests: Array<{ url: string; body: any; headers: Record<string, string> }> = [];
    const stderr: string[] = [];
    const mkFetch = (severity: "warning" | "error") =>
      (async (url: string, init: RequestInit) => {
        requests.push({ url, body: init.body ? JSON.parse(String(init.body)) : undefined, headers: init.headers as Record<string, string> });
        return new Response(JSON.stringify({
          report: { findings: [{ code: "TYPE_UNKNOWN", severity, consumer: "charge", reference: "state.x", summary: "unknown" }], references_checked: 1 },
          generated: { generator_version: "orch8-dataflow-v2", sequence_sha256: "abc", schema: {}, typescript: "// engine types\n", python: "" },
        }), { status: 200 });
      }) as unknown as typeof fetch;
    const out = join(tmp, "remote.ts");
    const env = { ORCH8_URL: "http://engine/api/v1", ORCH8_API_KEY: "k", ORCH8_TENANT_ID: "acme" };
    const code = await runCli(["--remote", fixturePath, "--strict", "--out", out], {
      stdout: () => {}, stderr: (t) => stderr.push(t), env, cwd: tmp, fetch: mkFetch("warning"),
    });
    expect(code).toBe(0);
    expect(readFileSync(out, "utf8")).toBe("// engine types\n");
    expect(requests[0].url).toBe("http://engine/api/v1/sequences/dataflow?strict=true");
    expect(requests[0].body).toMatchObject({ name: "checkout-flow", tenant_id: "acme", id: "00000000-0000-7000-8000-000000000000" });
    expect(requests[0].headers).toMatchObject({ "x-api-key": "k", "X-Tenant-Id": "acme" });
    expect(stderr.join("")).toContain("WARNING TYPE_UNKNOWN charge (state.x)");

    const idCode = await runCli(["--remote", "--id", "seq-1"], {
      stdout: () => {}, stderr: () => {}, env, cwd: tmp, fetch: mkFetch("error"),
    });
    expect(idCode).toBe(1);
    expect(requests[1].url).toBe("http://engine/api/v1/sequences/seq-1/dataflow");
  });
});
